services:
  # catalog.api:
  #   image: ${DOCKER_REGISTRY-}catalogapi
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalogdb:
    image: postgres:16
    
# catalog-db
volumes:
  postgres_catalog:
